In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
%matplotlib inline

In [17]:
GRID_DIM = 4
GRID_SIZE = GRID_DIM * GRID_DIM
A, A_ , B, B_ = np.array([0, 1]), np.array([4, 1]), np.array([0, 3]), np.array([2, 3])
LEFT, RIGHT, UP , DOWN = np.array([0, -1]), np.array([0, 1]), np.array([-1, 0]), \
                        np.array([1, 0]) 
A_REWARD = +5.0
B_REWARD = +10.0
# GAMMA = 0.9 
GAMMA = 1.
Pi_as = 0.25
ITERATIONS = 10000
ACTIONS = [LEFT, RIGHT , UP , DOWN]

In [18]:
def get_reward(location):
    if location[0] == 0 and location[0] == 0 :
        return 0
    if location[0] == GRID_DIM-1 and location[0] == GRID_DIM-1:
        return 0
    
    return -1
def get_state_reward(cur_state, action):
    if cur_state[0] == 0 and cur_state[1] == 0:
        return cur_state, 0  
    if cur_state[0] == GRID_DIM-1 and cur_state[1] == GRID_DIM-1:
        return cur_state, 0
    
    n_loc = cur_state + action
    if n_loc[0] >= GRID_DIM or n_loc[0] < 0 or n_loc[1] >= GRID_DIM or n_loc[1] < 0:
        return cur_state, -1
    else:
        return n_loc, -1

In [19]:
grid_world_v_pi = np.zeros((GRID_DIM, GRID_DIM))
for k in range(3):
    for i in range(GRID_DIM):
        for j in range(GRID_DIM):
            cur_action = ACTIONS[np.random.randint(0,3)]

            new_state, reward = get_state_reward(np.array([i, j]), cur_action)
            grid_world_v_pi[i,j] += GAMMA**k * reward
    print(grid_world_v_pi)

[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
[[ 0. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2. -2.  0.]]
[[ 0. -3. -3. -3.]
 [-3. -3. -3. -3.]
 [-3. -3. -3. -3.]
 [-3. -3. -3.  0.]]


In [39]:
v_pi = np.zeros((GRID_DIM, GRID_DIM))
count = 0
# value_grid 
for k in range(40):
    v_pi_ = np.zeros((GRID_DIM, GRID_DIM))
    v_action = np.zeros((GRID_DIM, GRID_DIM))
    for i in range(GRID_DIM):
        for j in range(GRID_DIM):
            max_action = None
            max_value = None
            actions_grid = [] 
            for index, act in enumerate(ACTIONS):
                cur_state = np.array([i, j])
                (n_i, n_j), reward = get_state_reward(cur_state, act)
                # equation 3.12
                v_pi_[i, j] += Pi_as * (reward + GAMMA * v_pi[n_i, n_j])
                if index == 0:
                    max_value = Pi_as * (reward + GAMMA * v_pi[n_i, n_j])
                    max_action = index
                else:
                    if max_value < Pi_as * (reward + GAMMA * v_pi[n_i, n_j]):
                        max_action = index
                        max_value = Pi_as * (reward + GAMMA * v_pi[n_i, n_j])
                v_action[i,j] = max_action
                
                
                
    count += 1
    if np.sum(np.abs(v_pi - v_pi_)) < 1e-4:
        break
    v_pi = v_pi_
    if k < 5 or (k > 5 and k % 10==0):
        print('K ', k)
        print(np.round(v_pi, decimals=1))
        print('Policy')            
        print(v_action)

K  0
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
Policy
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
K  1
[[ 0.  -1.8 -2.  -2. ]
 [-1.8 -2.  -2.  -2. ]
 [-2.  -2.  -2.  -1.8]
 [-2.  -2.  -1.8  0. ]]
Policy
[[0. 0. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]
 [0. 0. 1. 0.]]
K  2
[[ 0.  -2.4 -2.9 -3. ]
 [-2.4 -2.9 -3.  -2.9]
 [-2.9 -3.  -2.9 -2.4]
 [-3.  -2.9 -2.4  0. ]]
Policy
[[0. 0. 0. 0.]
 [2. 0. 0. 3.]
 [2. 0. 1. 3.]
 [0. 1. 1. 0.]]
K  3
[[ 0.  -3.1 -3.8 -4. ]
 [-3.1 -3.7 -3.9 -3.8]
 [-3.8 -3.9 -3.7 -3.1]
 [-4.  -3.8 -3.1  0. ]]
Policy
[[0. 0. 0. 0.]
 [2. 0. 0. 3.]
 [2. 1. 1. 3.]
 [1. 1. 1. 0.]]
K  4
[[ 0.  -3.7 -4.7 -4.9]
 [-3.7 -4.5 -4.8 -4.7]
 [-4.7 -4.8 -4.5 -3.7]
 [-4.9 -4.7 -3.7  0. ]]
Policy
[[0. 0. 0. 0.]
 [2. 0. 0. 3.]
 [2. 1. 1. 3.]
 [1. 1. 1. 0.]]
K  10
[[ 0.  -6.6 -9.  -9.7]
 [-6.6 -8.3 -9.  -9. ]
 [-9.  -9.  -8.3 -6.6]
 [-9.7 -9.  -6.6  0. ]]
Policy
[[0. 0. 0. 0.]
 [2. 0. 0. 3.]
 [2. 1. 1. 3.]
 [1. 1. 1. 0.]]
K  20
[[  0.   -9.7

Book Method

Policy Iteration

In [1]:
import numpy as np

def get_state_reward(cur_state, action):
    if cur_state[0] == 0 and cur_state[1] == 0:
        return cur_state, 0  
    if cur_state[0] == GRID_DIM-1 and cur_state[1] == GRID_DIM-1:
        return cur_state, 0
    n_loc = np.zeros(2)

    n_loc[0] = cur_state[0] + (action[0])
    n_loc[1] = cur_state[1] + action[1]
    n_loc = n_loc.astype(int)

    if n_loc[0] >= GRID_DIM or n_loc[0] < 0 or n_loc[1] >= GRID_DIM or n_loc[1] < 0:
        return cur_state, -1
    else:
        return n_loc, -1

In [2]:
GRID_DIM  = 4
LEFT, RIGHT, UP , DOWN = np.array([0, -1]), np.array([0, 1]), \
                        np.array([-1, 0]), \
                        np.array([1, 0]) 
ACTIONS = [LEFT, RIGHT, UP , DOWN]

Pi_as = 0.25

In [3]:
V_s = np.zeros((GRID_DIM, GRID_DIM))
pi_ = np.zeros((GRID_DIM, GRID_DIM)).astype(int)

policy_stable = False
count = 0
while not policy_stable:
    print('Iteration', count, policy_stable)
    policy_stable = True
    while True:
        delta = 0
        for i in range(GRID_DIM):
            for j in range(GRID_DIM):
                if (i,j)  != (0,0) and (i,j)!=(3,3):
                    v = V_s[i,j]
                    cur_loc = np.array([i, j])
                    action = ACTIONS[pi_[i, j]]
                
                    next_state, rew = get_state_reward(cur_loc, action )
                    V_s[i,j] = rew + V_s[next_state[0], next_state[1]]

                    delta = max(delta, abs(v - V_s[i,j]))
#                 print(delta)
        if delta < 3.:
            break

    for i in range(GRID_DIM):
        for j in range(GRID_DIM):
            old_action = pi_[i, j]
            values = []
            cur_loc = np.array([i,j])
            for action in ACTIONS:
                st, rew = get_state_reward(cur_loc, action)
                values.append(rew + V_s[st[0], st[1]])
            
            pi_[i,j] = np.argmax(values)
            if old_action != pi_[i, j]:
                policy_stable = False
    
    count += 1
    
print(V_s)
print(pi_)

Iteration 0 False
Iteration 1 False
Iteration 2 False
Iteration 3 False
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
[[0 0 0 0]
 [2 0 0 3]
 [2 0 1 3]
 [1 1 1 0]]


In [6]:
p_dash = []
for i in range(GRID_DIM):
    for j in range(GRID_DIM):
        old_action = pi_[i, j]
        values = []
        cur_loc = np.array([i,j])
        
        vp  = []
        for action in ACTIONS:
            st, rew = get_state_reward(cur_loc, action)
            values.append(rew + V_s[st[0], st[1]])
        max_value = max(values)
        for i , value in enumerate(values):
            if value == max_value:
                vp.append(i)
        
        p_dash.append(vp)
#         pi_[i,j] = np.argmax(values)

In [7]:
for i in range(GRID_DIM):
    print()
    for j in range(GRID_DIM):
        print(p_dash[i*GRID_DIM + j], '|' , end =" ")


[0, 1, 2, 3] | [1] | [1] | [0, 1, 2, 3] | 
[2] | [1] | [1] | [0, 1, 2, 3] | 
[2] | [1] | [1] | [0, 1, 2, 3] | 
[1, 2] | [1] | [1] | [0, 1, 2, 3] | 

### Value Iteration

In [37]:
# experimental method
v_pi = np.zeros((GRID_DIM, GRID_DIM))
count = 0
GAMMA = 1.
for k in range(10):
    v_pi_ = np.zeros((GRID_DIM, GRID_DIM))
    v_action = np.zeros((GRID_DIM, GRID_DIM))
    for i in range(GRID_DIM):
        for j in range(GRID_DIM):
            max_action = None
            max_value = None
            actions_grid = []
            values = [] 
            for index, act in enumerate(ACTIONS):
                cur_state = np.array([i, j])
                (n_i, n_j), reward = get_state_reward(cur_state, act)
                # equation 3.12
                values.append(Pi_as * (reward + GAMMA * v_pi[n_i, n_j]))
                if index == 0:
                    max_value = Pi_as * (reward + GAMMA * v_pi[n_i, n_j])
                    max_action = index
                else:
                    if max_value < Pi_as * (reward + GAMMA * v_pi[n_i, n_j]):
                        max_action = index
                        max_value = Pi_as * (reward + GAMMA * v_pi[n_i, n_j])
                v_action[i,j] = max_action
            v_pi_[i, j] = max(values)
                
                
    count += 1
#     if np.sum(np.abs(v_pi - v_pi_)) < 1e-4:
#         break
    v_pi = v_pi_
    print('K ', k)
    print(v_pi)
    print('Policy')            
    print(v_action)

K  0
[[ 0.   -0.25 -0.25 -0.25]
 [-0.25 -0.25 -0.25 -0.25]
 [-0.25 -0.25 -0.25 -0.25]
 [-0.25 -0.25 -0.25  0.  ]]
Policy
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
K  1
[[ 0.     -0.25   -0.3125 -0.3125]
 [-0.25   -0.3125 -0.3125 -0.3125]
 [-0.3125 -0.3125 -0.3125 -0.25  ]
 [-0.3125 -0.3125 -0.25    0.    ]]
Policy
[[0. 0. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]
 [0. 0. 1. 0.]]
K  2
[[ 0.       -0.25     -0.3125   -0.328125]
 [-0.25     -0.3125   -0.328125 -0.3125  ]
 [-0.3125   -0.328125 -0.3125   -0.25    ]
 [-0.328125 -0.3125   -0.25      0.      ]]
Policy
[[0. 0. 0. 0.]
 [2. 0. 0. 3.]
 [2. 0. 1. 3.]
 [0. 1. 1. 0.]]
K  3
[[ 0.       -0.25     -0.3125   -0.328125]
 [-0.25     -0.3125   -0.328125 -0.3125  ]
 [-0.3125   -0.328125 -0.3125   -0.25    ]
 [-0.328125 -0.3125   -0.25      0.      ]]
Policy
[[0. 0. 0. 0.]
 [2. 0. 0. 3.]
 [2. 0. 1. 3.]
 [1. 1. 1. 0.]]
K  4
[[ 0.       -0.25     -0.3125   -0.328125]
 [-0.25     -0.3125   -0.328125 -0.3125  ]
 [-0.3125   -0.328125

In [43]:

np.random.rand?

Book method for value iteration

In [8]:
import numpy as np

def get_state_reward(cur_state, action):
    if cur_state[0] == 0 and cur_state[1] == 0:
        return cur_state, 0  
    if cur_state[0] == GRID_DIM-1 and cur_state[1] == GRID_DIM-1:
        return cur_state, 0
    n_loc = np.zeros(2)
#     print(cur_state)
#     print(action)
    n_loc[0] = cur_state[0] + (action[0])
    n_loc[1] = cur_state[1] + action[1]
    n_loc = n_loc.astype(int)
#     n_loc  = cur_state + action.astype(int)
    if n_loc[0] >= GRID_DIM or n_loc[0] < 0 or n_loc[1] >= GRID_DIM or n_loc[1] < 0:
        return cur_state, -1
    else:
        return n_loc, -1

In [9]:
GRID_DIM  = 4
LEFT, RIGHT, UP , DOWN = np.array([0, -1]), np.array([0, 1]), \
                        np.array([-1, 0]), \
                        np.array([1, 0]) 
ACTIONS = [LEFT, RIGHT, UP , DOWN]

Pi_as = 0.25

# V = -np.abs(np.random.rand(GRID_DIM, GRID_DIM))
V = np.zeros((GRID_DIM, GRID_DIM))
V[0][0] = 0
V[GRID_DIM-1][GRID_DIM-1] = 0

count = 0
while True:
#     print(count)
    delta = 0
#     v_pi_ = np.zeros((GRID_DIM, GRID_DIM))
    for i in range(GRID_DIM):
        for j in range(GRID_DIM):
            if (i, j) != (0,0) and (i, j) != (3,3):
                v = V[i,j]
                values = [] 
                for _, act in enumerate(ACTIONS):
                    cur_loc = np.array([i, j])

                    st, rew = get_state_reward(cur_loc, act)

                    new_v = (rew + V[st[0], st[1]])
#                     print(st, cur_loc, rew, act, v)
                    values.append(new_v)

                V[i,j] = max(values)

                delta = max(delta, abs(v - V[i,j]))
        
    count +=1
    if delta < 1e-4:
        
        break

            
print(V)
actions_grid = np.zeros((GRID_DIM, GRID_DIM))
for i in range(GRID_DIM):
    for j in range(GRID_DIM):
        values = []
        for act in ACTIONS:
            cur_loc = np.array([i, j])
            st, rew = get_state_reward(cur_loc, act)
            values.append(rew + V[st[0], st[1]])
        actions_grid[i,j] = np.argmax(values)
print(actions_grid)

[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
[[0. 0. 0. 0.]
 [2. 0. 0. 3.]
 [2. 0. 1. 3.]
 [1. 1. 1. 0.]]


In [11]:
p_dash = []
for i in range(GRID_DIM):
    for j in range(GRID_DIM):
        old_action = pi_[i, j]
        values = []
        cur_loc = np.array([i,j])
        
        vp  = []
        for action in ACTIONS:
            st, rew = get_state_reward(cur_loc, action)
            values.append(rew + V_s[st[0], st[1]])
        max_value = max(values)
        for i , value in enumerate(values):
            if value == max_value:
                vp.append(i)
        
        p_dash.append(vp)
        
    
for i in range(GRID_DIM):
    print()
    for j in range(GRID_DIM):
        print(p_dash[i*GRID_DIM + j], '|' , end =" ")


[0, 1, 2, 3] | [1] | [1] | [0, 1, 2, 3] | 
[2] | [1] | [1] | [0, 1, 2, 3] | 
[2] | [1] | [1] | [0, 1, 2, 3] | 
[1, 2] | [1] | [1] | [0, 1, 2, 3] | 